export enum Status {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE'
  }

  export enum PaymentStatus {
    PAID_IN_FULL = "PAID_IN_FULL", 
    INSTALLMENT_PAID = "INSTALLMENT_PAID", 
    FAILED = "FAILED", 
    ARREARS_PAYMENT = "ARREARS_PAYMENT", 
    AWAITING_PAYMENT = "AWAITING_PAYMENT", 
    PROCESSING = "PROCESSING", 

    ACTIVE = "ACTIVE", 
    PENDING = "PENDING", 
    AWAITING_APPROVALS = "AWAITING_APPROVALS", 
    APPROVED = "APPROVED", 
    ON_WAITING_PERIOD = "ON_WAITING_PERIOD", 
    IN_SUSPENSE ="IN_SUSPENSE"
  }
  export enum FileType {
    DEATH_CERT = "DEATH_CERT", 
    BURIAL_ORDER = "BURIAL_ORDER", 
    DOCTORS_LETTER = "DOCTORS_LETTER", 
    POLICE_REPORT = "POLICE_REPORT", 
  }

  export enum PayoutStatus {
    PAID_IN_FULL = "PAID_IN_FULL", 
    INSTALLMENT_PAID = "INSTALLMENT_PAID", 
    FAILED = "FAILED", 
    ARREARS_PAYMENT = "ARREARS_PAYMENT", 
    AWAITING_PAYMENT = "AWAITING_PAYMENT", 
    PROCESSING = "PROCESSING", 
  }

  export enum Settings {
    INDIVIDUAL = "INDIVIDUAL", 
    GROUP = "GROUP", 
    BURIAL_SOCIETY = "BURIAL_SOCIETY", 
    COOPERATE = "COOPERATE", 
  }

  export enum Types {
    REMITTANCE = "REMITTANCE", 
    COMMISSION = "COMMISSION", 
  }