export enum Status {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE'
  }

  export enum PaymentStatus {
    ACTIVE = "ACTIVE", 
    PENDING = "PENDING", 
    AWAITING_APPROVALS = "AWAITING_APPROVALS", 
    APPROVED = "APPROVED", 
    AWAITING_DELETION = "AWAITING_DELETION", 
    ON_WAITING_PERIOD = "ON_WAITING_PERIOD", 
    PAID_IN_FULL = "PAID_IN_FULL", 
    INSTALLMENT_PAID = "INSTALLMENT_PAID", 
    FAILED = "FAILED", 
    ARREARS_PAYMENT = "ARREARS_PAYMENT", 
    IN_SUSPENSE ="IN_SUSPENSE"
  }

  export enum FileType {
    DEATH_CERT = "DEATH_CERT", 
    BURIAL_ORDER = "BURIAL_ORDER", 
    DOCTORS_LETTER = "DOCTORS_LETTER", 
    POLICE_REPORT = "POLICE_REPORT", 
  }